In [1]:
import numpy as np

#Matrix and Its Operations

M1 = np.array(([-5, 0], [4, 1]))
M2 = np.array(([6, 3], [2, 3]))

Sum = M1 + M2
difference1 = M2 - M1
difference2 = M1 - M2

print("Matrix and Its Operations")
print("")
print("Sum")
print(Sum)
print("")
print("Difference1")
print(difference1)
print("")
print("Difference2")
print(difference2)


Matrix and Its Operations

Sum
[[1 3]
 [6 4]]

Difference1
[[11  3]
 [-2  2]]

Difference2
[[-11  -3]
 [  2  -2]]
